### ISSUE TITLE
Using -r/require flag seems force CJS

### ISSUE THREAD

**Issue by rschristian** [lukeed/uvu#108]
## Reproduction
https://github.com/rschristian/uvu-require-reproduction

Fresh WMR app, with the Preact Uvu example (somewhat) copied in. Just with a bit of an alteration to the babel config to instead use the HTM transform that WMR uses (in prod, but this one is easily installable).

## Summary of problem

The issue seems to be that when using the require flag (`-r`) everything is interpreted to be CJS. `preact-iso` is shipped with `"type": "module"`, so it's very clearly ESM, and yet Uvu seems to try to `require()` it. Maybe this is user error, but it doesn't seem like that flag should alter module resolution. 

I've only just came across this and it's late here so I'll need to do more investigation (hopefully) tomorrow.

## Error Message

```
➜  ~/Projects/foobar git:(master) ✗ yarn test
yarn run v1.22.10
$ uvu tests -r esm -r @babel/register -i setup
/home/ryun/Projects/foobar/node_modules/pirates/lib/index.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ryun/Projects/foobar/node_modules/preact-iso/router.js
require() of ES modules is not supported.
require() of /home/ryun/Projects/foobar/node_modules/preact-iso/router.js from /home/ryun/Projects/foobar/public/header.jsx is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename router.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/ryun/Projects/foobar/node_modules/preact-iso/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Object.newLoader [as .js] (/home/ryun/Projects/foobar/node_modules/pirates/lib/index.js:104:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Tool Versions

Node: v14.16.0
Yarn: v1.22.10

**Comment by rschristian** [comment]
Oops, turns out it's an issue with `@babel/register`, nothing here! Sorry!

**Comment by lukeed** [comment]
Oh, cool 😅  Thanks for following up!

**Comment by rschristian** [comment]
Yeah, didn't realize `@babel/register` (i.e., I didn't read the docs) can't intercept Node's own resolution for native ESM which apparently puts me in a bit of a predicament for `preact-iso`, with it only shipping ESM. 

So into the rabbit hole of CJS, ESM, and Babel I go 😅

**Comment by lukeed** [comment]
It probably doesn't help you too much (aka you may have to use babel  for reasons), but I'd configure it to produce ESM output or just swap to esbuild-register for ESM final transformations.

**Comment by rschristian** [comment]
I've very much avoided learning Babel up until this point so I probably just need to play around with it a bit more, but as far as I know I only need it for doing JSX transformations on some WMR sources. Just need to figure out the winning pattern there.

**Comment by rschristian** [comment]
Though actually, this may still be an issue, just not as I originally framed it. With the require flag (`-r`) set to anything, [the user is locked into the CJS `uvu/run`](https://github.com/lukeed/uvu/blob/1d753576ffab2dd28b309bb5c296a43d0800321c/bin.js#L25). That, of course, will try to [use `require()` to load the test suite](https://github.com/lukeed/uvu/blob/1d753576ffab2dd28b309bb5c296a43d0800321c/run/index.js#L9), even if it's authored in ESM. 

Unless I'm misunderstanding, and that could certainly be possible, there seems to be an assumption that using Babel (or similar) means CJS, when that might not be the case?

**Comment by lukeed** [comment]
Yes, `-r` with uvu forces CommonJS version of `uvu/run`. This is because require hooks are exclusively a CommonJS thing

**Comment by rschristian** [comment]
Ah, fair enough.

**Comment by lukeed** [comment]
Yeah this is the disconnect that still exists in the ecosystem (until loader hooks standardize). You'll have to opt into CJS and then have it transform your source and test files.

This is the core of what the typescript example is doing. You can do it purely with babel too or with esbuild for the quicker boost & small config surface area.

**Comment by rschristian** [comment]
Makes sense.

I have gotten lucky and avoided manually dealing with transforms up to this point, so going through this for the first time and learning about the of troubled areas is certainly interesting
