### ISSUE TITLE
"Maximum call stack size exceeded" for assert.fixture()

### ISSUE THREAD

**Issue by bartveneman** [lukeed/uvu#115]
One of my fixture tests fails because of a `Maximum call stack size exceeded` error.

**OS**: MacOS 11.4
**Node**: v14.15.3
**uvu**: 0.5.1

```js
// json => readFileSync()
assert.fixture(JSON.stringify(analyze(css), null, 2), json)
```

This JSON is a 15.000+ lines file.

## Workaround

To avoid adding the arr.map() callback to the call stack for every line (15.000+) I'm using a for-loop.

```diff
+ // https://github.com/lukeed/uvu/blob/1d753576ffab2dd28b309bb5c296a43d0800321c/src/assert.js#L4-L8
-function dedent(str) {
-	let arr = str.match(/^[ \t]*(?=\S)/gm);
-	let min = !!arr && Math.min(...arr.map(x => x.length));
-	return (!arr || !min) ? str : str.replace(new RegExp(`^[ \\t]{${min}}`, 'gm'), '');
-}
+function dedent(str) {
+	let arr = str.match(/^[ \t]*(?=\S)/gm);
+	if (!Array.isArray(arr) || arr.length === 0) {
+		return str
+	}
+	let min = -1
+       // Workaround for arr.map() to avoid add each map(fn) to call stack
+	for (let index = 0; index < arr.length; index++) {
+		const el = arr[index].length
+		if (el > min) {
+			min = el
+		}
+	}
+	return (!min) ? str : str.replace(new RegExp(`^[ \\t]{${min}}`, 'gm'), '');
+}
```

Happy to submit a PR if you think this is a suitable solution and worth fixing.

**Comment by lukeed** [comment]
Ha, literally the _one_ time I use newer syntax instead of a for-loop 🤦 

PR would be great! How about this instead, which is only slightly modified & should still work:

```js
function dedent(str) {
  let arr = str.match(/^[ \t]*(?=\S)/gm);
  let i = 0, min = 1/0, len = (arr||[]).length;
  for (; i < len; i++) min = Math.min(min, arr[i].length);
  return len && min ? str.replace(new RegExp(`^[ \\t]{${min}}`, 'gm'), '') : str;
}
```

Thanks!

**Comment by bartveneman** [comment]
As a follow-up that may turn out to be helpful for anyone coming here: I claimed that `arr.map()` was the issue, but it turns out it was `Math.min()` that breaks when spreading a too large array.

[REPL](https://replit.com/@bartveneman/CallStackExceededLoop#index.js)

```js
// works!
const arr = new Array(150000).fill(0)
const min = arr.map(x => x)

// Breaks....
const arr2 = new Array(150000).fill(0)
const min2 = Math.min(...arr2)
```

**Comment by lukeed** [comment]
Are you saying that this issue is back, or are you just clarifying why the error was happening?

**Comment by bartveneman** [comment]
Sorry, was just trying to explain what was the *actual* issue. Everything still works fine! 🥳

**Comment by lukeed** [comment]
Ah ok cool, thanks! :)
