### ISSUE TITLE
Support for jsx transforms

### ISSUE THREAD

**Issue by subhero24** [lukeed/uvu#116]
Any plans for supporting .jsx file for the runner? Or what would be the easiest way to test run files with JSX syntax?

**Comment by lukeed** [comment]
Hey, no, this is the responsibility of something else you bring. You can use the `-r` hook to attach things. 

There is the [Preact example](https://github.com/lukeed/uvu/tree/master/examples/preact), which uses Babel, but it can be anything you want.
