### ISSUE TITLE
Use yellow and red colors for suites with partial and no tests passing

### ISSUE THREAD

**Issue by jasikpark** [lukeed/uvu#129]
Would it be possible to add color-coding to the test output, so that a test suite with zero passing tests doesn't output in green?

<img width="239" alt="image" src="https://user-images.githubusercontent.com/10626596/128583031-cf1ecbcf-ac5b-4570-9e60-74ebaa734a0d.png">

It took me a bit to figure out that this didn't say that all tests were passing 😅 you might respond with "just read" but I feel like the color is misleading?

Would it be possible to at least add a section in red for `Failed:  X`?

Thanks for the great tool btw!

**Comment by lukeed** [comment]
Can I see your full output?

Pass count is always green. Skipped is yellow because you purposefully write in `.skip` and so doesn't effect the exit code. Any errors will fill up your terminal with plenty of red that it shouldn't be unclear.

If you skip enough tests that you have 0 tests running, I would justifiably say that's a green 0 and and 0 exit code. You wrote that in & it behaved accordingly

**Comment by jasikpark** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/10626596/128583254-8edea5ee-8b9f-4f89-acad-c3fffd0b743f.png">
full output 😅 from https://github.com/snowpackjs/prettier-plugin-astro

**Comment by jasikpark** [comment]
> Can I see your full output?
> 
> Pass count is always green. Skipped is yellow because you purposefully write in `.skip` and so doesn't effect the exit code. Any errors will fill up your terminal with plenty of red that it shouldn't be unclear.
> 
> If you skip enough tests that you have 0 tests running, I would justifiably say that's a green 0 and and 0 exit code. You wrote that in & it behaved accordingly

It might make sense to add a warning message if someone runs a test suite containing only skips :thinking: but I would agree that passing on having all tests skip makes sense.

**Comment by lukeed** [comment]
You should move your test-utils file into your fixtures so that it's not being loaded. Also don't think you need to have `-i package.json` in the cli usage

**Comment by lukeed** [comment]
I don't want to add a condition for such a rare and weird edge case tbh. Esp since the end result is expected and gonna be the same anyway.

It feels like your tests aren't being awaited correctly, and that may be the test-utils causing things to freak out. Not at my computer but will have to check later

**Comment by jasikpark** [comment]
`"test": "uvu test -i fixtures -i test-utils.js",` left me with the same result as the above screenshot (without moving any of the files around)

**Comment by jasikpark** [comment]
Ah, so the reason why I'm getting "Passed: 0" with green output is https://github.com/lukeed/uvu/blob/d56753ec20928da1c22ff093cb07ce3c67613706/src/index.js#L140 that the tests aren't ending but also aren't throwing exceptions?

Maybe there needs to be a time requirement or something?

**Comment by jasikpark** [comment]
I've sorted out that https://github.com/snowpackjs/prettier-plugin-astro/blob/198bf46dd6b2ff5ecff9314ffadea2cf1db201a3/test/astro-prettier.test.js#L20-L27 seems to be the culprit - that test is failing in some way - commit 043a1070612eb2d38f14b3b0dbda03f986c8f49a messed things up

**Comment by jasikpark** [comment]
by alterting the test to this: 
```js
Prettier('can format a basic Astro file', async () => {
  const [src, out] = await getFiles('basic');
  assert.not.fixture(src, out);
  console.log('before format');
  try {
    const formatted = format(src);
  } catch (e) {
    if (typeof e == 'Error') {
      throw e;
    }
    throw new Error(e);
  }
  console.log('after format');
  assert.fixture(formatted, out);
});
```
I can get the suite to run correctly.. I'm not sure why it's failing there.

**Comment by lukeed** [comment]
Can I close this? I don't really want to adjust the colorization & the actual _issue_ you were running into is tracked by #130
