### ISSUE TITLE
Promises that never resolve skip subsequent tests

### ISSUE THREAD

**Issue by tom-sherman** [lukeed/uvu#134]
I think this is a bug, but maybe I'm holding it wrong?

```js
// tests/test.js
const { test } = require('uvu');

test('skips subsequent tests', async () => {
  await new Promise(() => {});
  throw new Error("isnt executed");
});

test("doesn't run", () => {
  throw new Error('doesnt run');
});

test.run();
```

This test file doesn't fail and doesn't run any tests. Tested in both node 16 and node 14.

Same behaviour using both the CLI and node directly.

```
$ npx uvu
tests/test.js

$ node tests/test.js
$
```

**Comment by tom-sherman** [comment]
So I think this is because that there are no tasks on the event loop when we encounter the `await new Promise(() => {});` and this operation doesn't schedule any tasks either. At this point Node is like "welp, nothing else is happening here better exit the process". The same reason that

```js
function main() {
  return new Promise(() => {});
}

main().then(() => console.log('done'));
```

Will exit pretty much immediately and never log anything.

**Comment by tom-sherman** [comment]
I think this could be solved by including some internal scheduler/observer for test functions. This would ensure that we always wait for these types of tests to complete.


```js
function neverResolves() {
  return new Promise(() => {});
}

function resolvesInstantly() {
  return Promise.resolve(5);
}

function promiseObserver() {
  const pendingPromises = new Map();
  let onSettledCb = () => {};

  const wrap = (p) => {
    let result = { state: 'pending' };

    p.then((value) => {
      result.state = 'resolve';
      result.value = value;
    }).catch((value) => {
      result.state = 'reject';
      result.value = value;
    });

    return {
      p,
      result,
    };
  };

  const checkPendingPromises = () => {
    for (const wrappedP of pendingPromises.values()) {
      if (wrappedP.result.state !== 'pending') {
        pendingPromises.delete(wrappedP.p);
        onSettledCb(wrappedP);
      }
    }
  };

  let interval;
  const POLL_DURATION = 1000;
  const startTicking = () => {
    // Check immediately so that we handle any promises that are gonna resolve on the current tick asap
    // If we called this synchronously then we would have to wait POLL_DURATION to handle these promises
    // I'm not sure how this would be done in the browser, setTimeout(checkPendingPromises, 0) maybe?
    setImmediate(checkPendingPromises);

    // Poll for pending promises
    interval = setInterval(() => {
      checkPendingPromises();
      if (!pendingPromises.size) {
        clearInterval(interval);
      }
    }, POLL_DURATION);
  };

  return {
    add: (p) => {
      pendingPromises.set(p, wrap(p));
      if (!interval) {
        startTicking();
      }
    },
    onSettled: (cb) => {
      onSettledCb = cb;
    },
  };
}

let observer = promiseObserver();
observer.onSettled(({ p, result }) => {
  console.log('done', result);
});
observer.add(neverResolves());
observer.add(resolvesInstantly());
```

**Comment by Katarn** [comment]
Ava supports catching such errors in tests.

```js
const test = require('ava');

test('foo', () => {
    return new Promise(() => {});
});
```

```bash
> npx ava --verbose test.js

× foo Promise returned by test never resolved

─
foo

Error: Promise returned by test never resolved

─

1 test failed
```

https://github.com/avajs/ava/blob/0edfd00865a7103d52b81406e4b4443bd2e8cf9a/lib/test.js#L557-L562

https://github.com/avajs/ava/blob/0edfd00865a7103d52b81406e4b4443bd2e8cf9a/lib/runner.js#L231-L243

Is it possible to do something like this in uvu?

**Comment by lukeed** [comment]
This is just how JavaScript works. Your initial example will never resolve in a regular Node program:

```js
await new Promise(() => {}).then(() => console.log('done'))
// ~> infinite await
```

As mentioned in this thread, it's only "solved" by adding a timer to each test, which is overhead and IMO should be purely opt-in. Because of that, I'm closing this in favor of #33 

In practice, this means that uvu will only apply a timer to tests when you specify a `--timeout` value. By default, there's not going to be any timer since it's more/unnecessary work for 99% of code. Overall, this is something that your JS programs _should not_ be doing, so there's no point in penalizing _everyone's_ test performance for the rare occasions that may actually need it.

**Comment by Katarn** [comment]
Can there be conflicts with fake timers when using the `--timeout` parameter? If so, how, in this case, to check the execution of event listeners? Ava, as far as I can see, dispenses without the use of timers.

**Comment by lukeed** [comment]
https://github.com/avajs/ava/blob/0edfd00865a7103d52b81406e4b4443bd2e8cf9a/lib/test.js#L583

**Comment by Katarn** [comment]
It seems to me that this is not how it works in this case. Here are some minimal examples:

```js
async function test() {
    await new Promise(() => {}).then(() => console.log('done'));
}

test();
```

```bash
$ node test.js 
$
```

In my case, the process ends, without endless waiting for the promise to be resolved.

---

```js
.on('beforeExit', () => {
    console.log(`unresolved promises count: ${unresolvedPromisesCounter}`);
});

async function test() {
    await new Promise(() => {}).then(() => console.log('done'));
}

let unresolvedPromisesCounter = 0;

// For simplicity, we assume that the test returns a promise,
// but in ava there is a check through isPromise()

unresolvedPromisesCounter++;

test().then(() => {
    unresolvedPromisesCounter--;
});
```

```bash
$ node test.js 
unresolved promises count: 1
```

**Comment by lukeed** [comment]
Sorry, I don't have the bandwidth right now to discuss JS mechanics.

Go into your `node` repl and enter the following, with each session separated by `---`

```js
await new Promise(() => {}).then(() => console.log('done'));
//=> never resolves, no "done"

---

async function test() {
    await new Promise(() => {}).then(() => console.log('done'));
}

await test();
//=> never resolved; no "done"

---

async function test() {
    await new Promise(() => {}).then(() => console.log('done'));
}

test().then(() => {
  console.log('hi?');
});
//=> Promise {
//=>   <pending>,
//=>  ...
//=> }
//=> no "hi?" or "done"
```

Because the Promise never resolves _or throws_, you can never proceed beyond the Promise itself. This also means you can't use a `finally` block or `.finally()` step...since nothing progresses. The third example only prints anything at all because it queue & never awaited.

Assigning it to a variable & then waiting for it will result in the same.

```js
aaa = test().then(console.log)
//=> Promise {
//=>   <pending>,
//=>   ...
//=> }

await aaa;
//=> never resolves
```

You can't get around this without some form of artificial timer/scheduling system.

The plan laid out in https://github.com/lukeed/uvu/issues/134#issuecomment-989068910 is the way forward.

**Comment by tom-sherman** [comment]
@lukeed Sorry for not being clear about the original intention of this issue - the behaviour I'm describing is that tests are skipped in some scenarios, which could lead to false positive test passes.

Maybe I'm missing something but #33 appears to be a feature request to control the timeout of tests, I was raising a point about the first test in my example causing the second test not to ever execute.

**Comment by Katarn** [comment]
@lukeed Returning to this issue. We're talking about running tests from the console, not from the browser. The examples you suggested in https://github.com/lukeed/uvu/issues/134#issuecomment-989589655 comment and should not be resolved. The important thing is that node terminates its process even if the promises are not resolved.

And my suggestion in comment https://github.com/lukeed/uvu/issues/134#issuecomment-989582395 was just to catch the number of unresolved promises. In ava, they are perfectly caught without the use of timeout methods. The use of timeouts is optional there.

Try it online: https://onecompiler.com/nodejs/3xywnx3x2

**Comment by tom-sherman** [comment]
After thinking about this a little I really think this is a separate issue to timeouts.

A test runner _must_ ensure that test functions run to completion or throw an error. To me this is a core invariant a test runner must uphold. In other words tests should have two final states: "passed" and "failed". Currently this behaviour in uvu introduces a third state of "not complete" but surfaces the result to the user as "passed".

@lukeed Do you have any additional thoughts on this? I'd love for this issue to be reopened - I'm happy to implement @Katarn suggestion above.

**Comment by tom-sherman** [comment]
```js
await new Promise(() => {}).then(() => console.log('done'))
```

@lukeed You say that this code hangs infinitely, this is not the case. Both node and deno exit the process with a non-zero exit code in these situations. All I'm asking is for uvu to respect this behaviour.
