### ISSUE TITLE
Data driven tests

### ISSUE THREAD

**Issue by nulltoken** [lukeed/uvu#141]
👋 Hello @lukeed. We're current relying (a lot ;-) ) on jest `test.each()` feature.

Do you plan to add parameterized tests to uvu? Or maybe is there a way you could share to leverage the current API and make this happening already?

**Comment by lukeed** [comment]
Hello~! 

I probably wouldn't include it directly, but you could write a tiny little wrapper function to accomodate your needs:

```js
async function each(data, setup) {
  await Promise.all(data.map(setup));
}

// ---

import { suite } from 'uvu';
import * as assert from 'uvu/assert';

each([
  {a: 1, b: 1, expect: 2},
  {a: 1, b: 2, expect: 3},
  {a: 2, b: 1, expect: 3},
], ({ a, b, expect }) => {
  let test = suite(`add(${a}, ${b})`);

  test(`returns ${expect}`, () => {
    assert.is(a + b, expect);
  });
  
  test(`returned value not be greater than ${expect}`, () => {
    assert.not.ok(a + b > expect);
  });
  
  test(`returned value not be less than ${expect}`, () => {
    assert.not.ok(a + b < expect);
  });

  return test.run();
});
```

With #113 complete, then the `test.run()` part will be a promise, so you can have control flow for asynchronous test suites. Without that, things will still work, but only thru a fire-and-forget kinda pattern.

There's also a `describe` import coming. You can use [this helper](https://github.com/lukeed/uvu/issues/43#issuecomment-740817223) for the time being. Both are just a shorthand for setting up a `suite` and calling the `suite.run` afterwards. That combo would look something like this:

```js
import { describe } from 'uvu';

each([
  // ...
], ({ a, b, expect }) => {
  return describe(`add(${a}, ${b})`, it => {
    it(`returns ${expect}`, () => {
      // ...
    });

    // ...
  });
});
```

**Comment by nulltoken** [comment]
@lukeed Neat! Thanks a lot for the quick response.

Would you happen to have a TypeScript version of the `describe` helper you could share?

**Comment by lukeed** [comment]
```ts
import type { Test } from 'uvu';

type Describer = (it: Test) => Promise<void> | void;

function describe(name: string, hook: Describer): void {
  const t = suite(name);
  hook(t);
  t.run();
}
```

**Comment by nulltoken** [comment]
@lukeed <3
