### ISSUE TITLE
[question] does `uvu/assert` have something like ava's `t.plan()`

### ISSUE THREAD

**Issue by stefanprobst** [lukeed/uvu#150]
hi, does `uvu/assert` have something similar to AVA's [`t.plan()`](https://github.com/avajs/ava/blob/main/docs/recipes/when-to-use-plan.md) or [`expect.assertions()`](https://jestjs.io/docs/expect#expectassertionsnumber)? thanks!

**Comment by lukeed** [comment]
Hey there, no it doesn't. This is because async/await is supported out of the box and there's no need for another asynchronous controller.

You can replicate it by tracking your own counter.

```js
test("hello", () => {
  let plan = 10;
  for (let i=0; i<10; i++) {
    assert.type(i, 'number');
    plan--;
  }
  assert.is(plan, 0, 'all 10 plans ran');
})
```

Hope that helps
