### ISSUE TITLE
feat: type assertion

### ISSUE THREAD

**Issue by privatenumber** [lukeed/uvu#156]
## Description
Would like to be able to assert types like this:

```ts
assert.is<string>(value, 'string value');
```

**Comment by Beraliv** [comment]
@privatenumber might be solved with https://github.com/lukeed/uvu/issues/169 as I want to have stricter types there (the type will be infered from `actual` value which is usually the source of truth

**Comment by lukeed** [comment]
Yes, I know this came first, but closing in favor of #169 as it encompasses more items too
