### ISSUE TITLE
Workaround for Node.js 10

### ISSUE THREAD

**Issue by ai** [lukeed/uvu#162]
Hi. We are [moving](https://github.com/postcss/postcss/pull/1665) PostCSS to `uvu` (since your test runner is the best one).

Unfortunately, we still need tot support Node.js 10. I know that you do not support it officially (because of ESM).

But maybe you know a way to run it under Node.js 10 on our own risk? For instance, with some ESM → CJS runtime compiler?

Don’t worry, if not, we will made simple script test for Node.js 10.

**Comment by lukeed** [comment]
Hey, cool!

I actually do. uvu supports all the way to Node 8, but you have to run it in CommonJS mode for obvious reasons.

If you don't want the entire test matrix to be in CommonJS, then your best approach is to have two test scripts and rely on GitHub Actions to run the correct step(s) for the appropriate Node version match. 

```js
  "scripts": {
    "test:legacy": "uvu -r esm tests",
    "test:native": "uvu tests"
  }
```

I know I've done this in some of my repos but I can't remember any off hand atm

**Comment by ai** [comment]
Thanks!
