### ISSUE TITLE
add ava4 to benchmarks

### ISSUE THREAD

**Issue by iambumblehead** [lukeed/uvu#171]
ava4 isn't released yet, but it would be great to see it compared with uvu https://github.com/avajs/ava/discussions/2883

**Comment by lukeed** [comment]
When it's released (and stable) I will update it in the benchmarks.

**Comment by iambumblehead** [comment]
ava4 is released! https://www.npmjs.com/package/ava https://github.com/avajs/ava/releases/tag/v4.0.0

**Comment by iambumblehead** [comment]
@lukeed ^^
