### ISSUE TITLE
Error on non-flat node_modules envs like PNPM

### ISSUE THREAD

**Issue by XiNiHa** [lukeed/uvu#189]
I'm currently using Yarn with `nodeLinker: pnpm`, and one of my dependencies are using `uvu/assert`.
The problem is that `uvu/assert` imports from `uvu/diff` and since `uvu` is not specified as `uvu`'s dependency, it is impossible to resolve the import.
Changing the import from `uvu/diff` to `../diff` by hand fixed the issue.

**Comment by lukeed** [comment]
No. Your linker is wrong / behaving incorrectly. This is standard Node resolution logic

**Comment by lukeed** [comment]
It’s known as self-referential imports
