### ISSUE TITLE
TypeScript with dynamic import

### ISSUE THREAD

**Issue by vanyauhalin** [lukeed/uvu#194]
Hi. I'm [trying to use](https://github.com/vanyauhalin/attachment/tree/d0369859bddc97320fcfa2dacd481f1278a8ed1a/uvu/dynamic-import) dynamic import with typescript but have some problems. Changing `import` to `require` solves this problem.

```sh
$ pnpm run test 

> uvu-dynamic-import@ test /Users/vanyauhalin/Documents/code/uvu-dynamic-import
> uvu -r tsm test

handler.ts
index.ts
✘   (0 / 1)

   FAIL  "dynamic import"
    Cannot find module '/Users/vanyauhalin/Documents/code/uvu-dynamic-import/test/handler' imported from /Users/vanyauhalin/Documents/code/uvu-dynamic-import/test/index.ts




  Total:     1
  Passed:    0
  Skipped:   0
  Duration:  1.67ms

 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by rschristian** [comment]
This doesn't seem to be related to `uvu`, as you're having a transpilation issue.

You'll likely want to track https://github.com/lukeed/tsm/issues/27 for this.
