### ISSUE TITLE
[Feature request] ability to test a file. 

### ISSUE THREAD

**Issue by peterbe** [lukeed/uvu#197]
Running `uvu tests/some-directory` works and runs all 25 files in there. But `uvu tests/some-directory/specific-file.js` fails. 
You get 
```
Error: ENOTDIR: not a directory, scandir ...
```
So you have to type `uvu tests/some-directory specific-file.js` (note the replaced `/` for a space ` `)
It's not horrible but it's counter-intuitive and it prevents me from using tab completion.

**Comment by lukeed** [comment]
For single file, you should run `node path/to/file.js`

**Comment by peterbe** [comment]
> For single file, you should run `node path/to/file.js`

Wow! Didn't think about that. That works because there's no magic. That `.run()` is the "framework". 

I would still venture to say that I'm making a point. About usability. It wouldn't be hard to do something like:

```js
let fileFilter = null
let pattern = process.argv[4]
if (lstatsSync(pattern).isFile()) {
  fileFilter = path.basename(pattern)
  pattern = path.dirname(pattern
}
...rest of uvu...
```

**Comment by lukeed** [comment]
No, this is an intentional design goal of uvu. The CLI should only do extra work to autoload multiple files on your behalf; basically as a shorthand (and faster, if using require hooks) for:

```sh
$ find <dir> -type f -name "<pattern>" -exec node {} \;
```

**Comment by peterbe** [comment]
It's your call, and I respect that, but something that's come up for me is that:

- When switching from `uvu` to `node` I can no longer use `--bail`. E.g. `node tests/routing/redirects.js --bail` will not exit on the first assertion failure. 
- To use `uvu` I have to inject a space between the directory and the file, so `uvu node tests/routing redirects.js --bail` but now it also runs `tests/routing/top-developer-site-path-redirects.js` which I don't want it to. Because the pattern "redirects.js" matches multiple files.
