### ISSUE TITLE
uvu's GitHub Action not actually testing different OS

### ISSUE THREAD

**Issue by rdmurphy** [lukeed/uvu#20]
Hello! 👋 

I just noticed the `os` field is present in the `matrix` for the action but it's not actually being used to set `runs-on` — it looks like everything is still running on `ubuntu-latest`.

https://github.com/lukeed/uvu/blob/a34b44d6c593acd5e0fcb807b33ddb7dbecfa9df/.github/workflows/ci.yml#L14-L19

(Only noticed this because I'm tweaking an action of mine that uses `uvu` and was trying to borrow from `uvu`'s action. 🙃 )

**Comment by lukeed** [comment]
Oh shoot – thanks!

Yeah, I assembled this CI by copy-pasting from some of my other repos.
Fixing now :)
