### ISSUE TITLE
Typescript example: Can't use ES modules imports with Node.js AND uvu

### ISSUE THREAD

**Issue by cristianfalcone** [lukeed/uvu#22]
Thanks for the tool @lukeed!

I'm having an issue with the Typescript example:

I'm trying to use ES modules directly, with the latest version of Node.js, but I can't make test modules to work at the same time, when using imports between source modules.

I added the following (which I think it's a pretty common use case), to the typescript example you provided:

- Added `"type": "module"` to `package.json` file, so I can use ES modules with Node.js
- Added `src/main.ts` file with the following content:

```typescript
import { sum } from './math'

export function run() {
    console.log(sum(2, 3))
}

run()
```
- Added `tests/main.ts` file with the following content:

```typescript
import { test } from 'uvu';
import * as assert from 'uvu/assert';
import * as main from '../src/main';

test('run', () => {
    assert.type(main.run, 'function');
});
```
- Build and test:

```
yarn build && yarn test
```

Tests work! But when I try to run emmited files with Node.js, got the following error:

```
node build/main.js
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/cristian/projects/uvu-typescript-example/build/math' imported from /home/cristian/projects/uvu-typescript-example/build/main.js
```

This is because ES modules imports need explicit file extension. So I fix the issue adding imports file extensions to `src/main.ts` (which is supported by Typescript)

```typescript
import { sum } from './math.js'
...
```

Now building and running main file works:

```
yarn build && node build/main.js
yarn run v1.22.4
$ tsc
Done in 2.44s.
5
```

but tests don't :( (got the following error):

```
yarn test
yarn run v1.22.4
$ uvu -r ts-node/register tests
(node:28693) UnhandledPromiseRejectionWarning: Error: Cannot find module './math.js'
```

Tried different `tsconfig.json` configurations, but can't make the emmited files and test files to work at the same time.

**Comment by lukeed** [comment]
Hey,

Can you please send me a reproduction repo & let me know what version of Node you're using?
That's the surest way to know I'm replicating your issue correctly :)

**Comment by cristianfalcone** [comment]
Sure!

Repo: https://github.com/cristianfalcone/uvu-typescript-example

Node.js version:
```
node -v
v14.5.0
```

;)

**Comment by lukeed** [comment]
Thank you!

These changes are necessary for `build` and `test` to work:

```diff
// src/main.ts
- import { sum } from './math.js'
+ import { sum } from './math'

// tests/main.ts
+
+test.run()
```

Verified on latest 10.x, 12.x, and 14.5.0

**Comment by cristianfalcone** [comment]
Yes, sorry! I forgot the `test.run()`

But the execution still does not work (the `build` and `test` scripts do work, but not the following command:)

```
node build/main.js
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/cristian/projects/uvu-typescript-example/build/math' imported from /home/cristian/projects/uvu-typescript-example/build/main.js
```

**Comment by lukeed** [comment]
Oh, sorry – forgot the second half of your predicament. 
TypeScript can't output `mjs` files (which `type: "module"` addresses) nor modify the output links (which is still _unaddressed_ & causes the error you see).

I'd recommend passing everything through Rollup – here's an example [TS+Rollup setup](https://github.com/lukeed/typescript-module).

But if you want to use this example as your boilerplate, you can do so by following this guide: https://github.com/microsoft/TypeScript/issues/18442#issuecomment-581738714

You only need step 3: `--experimental-specifier-resolution=node`
With that, you invoke the OG module-resolution algorithm which allows you to have extension-less imports

```sh
$ node --experimental-specifier-resolution=node build/main.js
#=> 5
```

**Comment by cristianfalcone** [comment]
Oh! That was the config I was looking for!

Thanks a lot @lukeed! Nice tool!

**Comment by lukeed** [comment]
You're welcome, happy to help! :)
