### ISSUE TITLE
(question) Missing lock file

### ISSUE THREAD

**Issue by oriSomething** [lukeed/uvu#223]
After looking `.gitignore`, I saw there are no lock files. What's the reason?

**Comment by lukeed** [comment]
Doesn’t matter to end user. Is just a lot of noise in PRs and CI should always pick up latest dependency versions when testing cuz users will also be installing latest versions of each semver range

**Comment by lukeed** [comment]
Lock files are meant to lock versions (which a library with runtime “dependencies” should never want) and are meant to speed up installs for CI/maintainers (but it’s already very fast)
