### ISSUE TITLE
Add support for focused tests

### ISSUE THREAD

**Issue by marvinhagemeister** [lukeed/uvu#24]
When developing code I tend to focus on single tests one by one. As an avid `console.log` debugger type of person I quickly get overwhelmed when logging statements from unrelated test cases litter stdout. For that reason I wonder if it may be feasible to add something like that to `uvu`.

Example from Mocha/Jest:

```js
// Whole suites or single tests can be focused
describe.only("suite", () => {
  it.only("single test", () => {
    // ...
  });
});
```

Example from Jasmine:

```js
// Whole suits or single tests can be focused
fdescribe("suite", () => {
  fit("single test", () => {
    // ...
  });
});
```

**Comment by lukeed** [comment]
We have `suite.only` (and implicitly, `teat.only`) already. You can also add multiple `only` modifiers per suite to slowly turn tests back "on" as you're ready. I do this quite often too -- we share the same approach 😅

https://github.com/lukeed/uvu/blob/master/docs/api.uvu.md#suiteonlyname-callback

**Comment by marvinhagemeister** [comment]
ohhh, whoops! Should've read the docs more carefully! :man_facepalming:

**Comment by lukeed** [comment]
Haha & I should highlight them better 😅 

Suites can be toggled off by commenting out their `run()` calls. 
If you want to target a specific test file, you can just `node path/to/file.js` directly.
