### ISSUE TITLE
Match a regex in uvu/assert

### ISSUE THREAD

**Issue by moroshko** [lukeed/uvu#34]
Is this the best way to match a regex now?
```js
assert.ok(myRegex.test(output));
```
Would be nice to have:
```js
assert.match(output, myRegex);
```

**Comment by lukeed** [comment]
It is for now. I like this idea though.

if you're willing, please feel free to send a PR where `assert.match` and `assert.not.match` can accept a RegExp or a String. String maps to `actual.includes(expect)`

**Comment by moroshko** [comment]
You are too quick @lukeed 😄 
Thanks for everything you do for the JS community!
