### ISSUE TITLE
Add '--findRelatedTests' to cli

### ISSUE THREAD

**Issue by MrMarble** [lukeed/uvu#36]
Hello @lukeed,

I love uvu but I think it is missing one of the biggest features, the ability to run tests on a pre-commit hook.

Jest does that with the `--findRelatedTests <spaceSeparatedListOfSourceFiles>` cli option (here is the [doc link](https://jestjs.io/docs/en/cli#--findrelatedtests-spaceseparatedlistofsourcefiles))

I'm not sure if this will be an easy thing to implement but sure it will be usefull!

**Comment by lukeed** [comment]
Hey,

Thank you for the idea, but as you alluded to, I think this may be too much to implement without much real benefit. Maybe one day something like this will exist (perhaps through an `uvu` extension layer?) but not at this point, I'm afraid.

Appreciate the suggestion! Didn't know that existed in Jest either.
