### ISSUE TITLE
Some node assert functions prevent the rest of a suite from running

### ISSUE THREAD

**Issue by mwanji** [lukeed/uvu#40]
This is strange, so maybe I'm doing something wrong. I've created a repo to demonstrate the issue: https://github.com/mwanji/uvu-node-assert-bug

I have a suite that uses node's built-in assert library. It gives the following result:

![image](https://user-images.githubusercontent.com/58760/89470721-bcb33880-d77c-11ea-93b2-d2f3c9989167.png)

If I modify the third test to the following, only the first two tests are run (or, at least, reported to have run):

```javascript
tests('Test 1', () => {
  assert.strictEqual('a', 'b');
});
```
![image](https://user-images.githubusercontent.com/58760/89470796-eb311380-d77c-11ea-8f3a-41f4613d12de.png)

So far, I've found that a failing `assert.strictEqual` or `assert.deepStrictEqual`, for example, will cause this situation. I experience the same issue when running the file with `node ./index.js`.

Node version: 12.18.3
OS: MacOS 10.15.6

**Comment by lukeed** [comment]
Hey~! There are two things going on:

1) When using `node index.js` approach on 12.18+ you're relying on Node's native ESM resolution. As it stands, there's an issue with `diff` in that it can't support native ESM yet (https://github.com/kpdecker/jsdiff/issues/292) - I'm waiting on response from them before continuing with #7 

2) To get around this, you have to use the `esm` package, which I see that you've already installed. To set that up correctly, move your `index.js` to `test/index.js` and then change your `"test"` npm script:

    ```diff
    - "test": "uvu"
    + "test": "uvu -r esm test"
    ```

    After you've done that, you can uncomment all the assertions and run `npm test`:

    ```
      Total:     5
      Passed:    1
      Skipped:   0
      Duration:  4.79ms
    ```

    Similarly, if you want to do the `node` path, you can do `node -r esm test/index.js` and get the same results.

---

All that said, I do see that I need to fix my formatting for native `assert` errors. It's listing everything as `undefined` in the diff, which isn't correct.

In the meantime, I advise you use `uvu/assert` instead:

```diff
- import assert from 'assert';
+ import * as assert from 'uvu/assert';
```

**Comment by mwanji** [comment]
@lukeed Thanks for the very detailed instructions, they're super helpful!
