### ISSUE TITLE
Bug in array comparison with undefined elements

### ISSUE THREAD

**Issue by TehShrike** [lukeed/uvu#44]
Reproduction:

```js
import * as assert from 'uvu/assert'
assert.equal([ `foo` ], [ undefined ])
```

Cause: https://github.com/lukeed/uvu/blob/1e24299effa19e1a4e07e999b245d5b81c03219d/src/diff.js#L53

`JSON.stringify(undefined)` returns `undefined`, which causes the `.split(/\r?\n/g)` to fail with:
> Cannot read property 'split' of undefined  (undefined)

**Comment by lukeed** [comment]
Ah, thank you. I should probably be formatting values in the same way that I'm dealing with output so that NaN/undefined are preserved
