### ISSUE TITLE
svelte tests (prop change)

### ISSUE THREAD

**Issue by jerrythomas** [lukeed/uvu#48]
I was able to implement tests using the example in the `svelte` folder. However, I am struggling with one scenario.

A component with property that can be changed from a parent component. The tests I wanted to do was checking that when the property value is updated, the rendered object changes. I think the svelte marks the property as dirty and the fragment is rerendered. 

Any suggestions on how to achieve this using `uvu`. What should a helper function to modify props and rerender the component look like?

**Comment by lukeed** [comment]
Hey,

The `ENV` helper included in the example returns a `{ container, component }` object: https://github.com/lukeed/uvu/blob/master/examples/svelte/tests/setup/env.js#L34

While the example tests only make use of `container`, you can grab the `component` and work with it directly using the [Svelte Component API](https://svelte.dev/docs#$set). Something like this should do the trick:

```js
// NOTE: not tested

test('should update `count` prop', () => {
  const { container, component } = ENV.render(Count, { count: 99 });

  assert.snapshot(
    container.innerHTML,
    `<button id="decr">--</button> <span>99</span> <button id="incr">++</button>`
  );

  component.$set({ count: 123 });

  assert.snapshot(
    container.innerHTML,
    `<button id="decr">--</button> <span>123</span> <button id="incr">++</button>`
  );
});
```

For complex, async-based updates, you'll probably have to add your own `ENV` helper that relies on `svelte.tick`, resulting in a helper that's similar to [`ENV.fire`](https://github.com/lukeed/uvu/blob/master/examples/svelte/tests/setup/env.js#L43).

Hope that helps!
