### ISSUE TITLE
CLI question

### ISSUE THREAD

**Issue by benmccann** [lukeed/uvu#67]
At the very end of https://github.com/lukeed/uvu/blob/master/docs/cli.md it says 

```
# Before
$ uvu -r esm tests
$ uvu -r ts-node/register tests

# After
$ uvu -r esm tests/math.js
$ uvu -r ts-node/register tests/math.ts
```

Are the last two `uvu` commands supposed to be `node`?

**Comment by lukeed** [comment]
Ah yup, thanks!
