### ISSUE TITLE
Native ESM Support

### ISSUE THREAD

**Issue by lukeed** [lukeed/uvu#7]
I have this 98% completed in local branch.

Allows you to run `uvu` with native ESM purely, making my current usage of `-r esm` completely optional.
This also has to maintain functionality within browsers, which will come for free.

**Comment by lukeed** [comment]
Will still be completed in the next day or two. Ran out of OSS time for the day~

**Comment by Hotell** [comment]
Luke is our hero !

**Comment by calebeby** [comment]
Hey Luke! I'd love to see this feature shipped! Is there anything I can help with?

**Comment by lukeed** [comment]
You can check it out on `uvu@next` right now.

I am/was not actively advertising it because it throws syntax errors in Node 8.x and Node 10.x – I'm being stubborn and want to hold onto support for those versions. I feel like there must be a way

**Comment by FredKSchott** [comment]
Node v8 is out of LTS no longer receiving updates, and enough major packages have dropped support that I rarely see anyone still using it (although they do exist). 

Node v10 is trickier... not out of LTS until 2021. Would it be possible to provide Node v10 support via a separate entrypoint (`uvu/cjs` or `uvu/node10`) that gets built at publish time (ESM->CJS via rollup, for example?)

**Comment by lukeed** [comment]
Right. Node 8.x (and 10) are support goals simply because I have older packages that I'd like to test with uvu, so that they have a single CI workflow that covers all Node versions. I don't necessarily plan to have all modules raise their `engines` floor simply because Node bumped. With enough dependents, that causes more harm than good to the ecosystem -- especially if the code isn't changing.

**Comment by lukeed** [comment]
Last night [`dequal@2.0.0`](https://github.com/lukeed/dequal/releases/tag/v2.0.0) went out, which added native ESM support (among other things). Now the remaining blocker for _pure_ ESM resolutions is https://github.com/kpdecker/jsdiff/pull/293

I still have to figure out my Node 8.x and 10.x workarounds -- haven't had time to dig back into that yet but I remain hopeful.

**Comment by talentlessguy** [comment]
@lukeed oh, waiting then :)

**Comment by talentlessguy** [comment]
@lukeed it's finally released!!!

I mean jsdiff with the fix

https://github.com/kpdecker/jsdiff/commit/d358a573dc38fb89dd5ee296805e29f75c932a58

**Comment by FredKSchott** [comment]
Woo!

**Comment by talentlessguy** [comment]
Is Native ESM still not supported by uvu because it still has an old (4.0.2) version of jsdiff?

or it should work already?

**Comment by TrySound** [comment]
uvu@next works fine

**Comment by lukeed** [comment]
Now available in v0.5.0 (stable) :)

**Comment by FredKSchott** [comment]
woo!
