### ISSUE TITLE
Proposal: Add example for Uvu + Puppeteer

### ISSUE THREAD

**Issue by AlexVipond** [lukeed/uvu#75]
Today I got a really fun setup working: Uvu (0.5.0 using native ES module support) for writing and running tests and assertions, and Puppeteer for evaluating code in the browser during a test.

```js
MySuite('can fetch data!', async ({ page }) => {
  const fetchedData = await page.evaluate(async () => {
    const result = await fetch('https://httpbin.org/get')
    return await result.json()
  })

  assert.ok(fetchedData)
})
```

I'm enjoying how minimalist it is—I can bundle my code however I want and build my app however I want. When it's time to test, I just need to spin up the app's development server, then I'm free to use Uvu and Puppeteer to visit pages and run test code.

@lukeed I can pull request an example setup if that's fine by you?

There's more than one way to make this work, but `before` and `after` hooks probably are best for most cases:

```js
import puppeteer from 'puppeteer-core'

MySuite.before(async context => {
  const browser = await puppeteer.launch(),
        page = await browser.newPage()

  context.browser = browser
  context.page = page
})

MySuite.after(async ({ browser }) => {
  await browser.close()
})
```

**Comment by lukeed** [comment]
Sure, sounds great! I may have an uvu extension coming that does a similar thing, but like with the other `/examples` it's nice to show the raw bits of this stuff.
