### ISSUE TITLE
Suggestion: an integration with esbuild to replace `ts-node/register` and `@babel/register`

### ISSUE THREAD

**Issue by hronro** [lukeed/uvu#79]
Since one of the main aim of uvu is fast, use [esbuild](https://github.com/evanw/esbuild) to replace `babel` or `tsc` would make unit tests with `uvu` much faster for end users.

**Comment by lukeed** [comment]
Yup! On my list. But I've had issues with `esbuild-register` so wasn't going to add that as an official example until it worked smoothly.

**Comment by eyelidlessness** [comment]
Just want to report that I was able to get this working fairly painlessly with [Estrella](https://github.com/rsms/estrella), like so:

```js
// ./scripts/test.js
// @ts-check

import del      from 'del';
import estrella from 'estrella';
import globby   from 'globby';
import path     from 'path';

(async () => {
  const cwd = process.cwd();

  const [ , args ] = estrella.cliopts.parse();
  const [ testDirName = 'test' ] = args;
  const entry = await globby(path.resolve(cwd, testDirName, '**/*.test.ts'));
  const outDir = path.resolve(cwd, './.test');

  estrella.build({
    cwd,
    entry,
    minify:    false,
    outdir:    outDir,
    run:       `npx uvu ${JSON.stringify(outDir)}`,
    sourcemap: 'inline',

    async onStart() {
      await del(outDir);
    },
  });
})();
```

Usage:

```sh
node ./scripts/test.js
```

Watch:

```sh
node ./scripts/test.js -w
```

Easy peasy! Obviously, any of the details of this may be changed. It does write to the filesystem, so if that's something you're really trying to avoid you'll want something like `esbuild-register` or [ts-eager](https://github.com/mhart/ts-eager). But wanted to share my solution in case it helps.

**Comment by natemoo-re** [comment]
As a possible alternative to `esbuild-register`, I had a smooth experience getting `uvu` working with [`@swc-node/register`](https://github.com/Brooooooklyn/swc-node)!

**Comment by privatenumber** [comment]
FYI `uvu -r esbuild-register` works fine for me

**Comment by eyelidlessness** [comment]
FWIW, last I checked both `@swc-node/register` and `esbuild-register` only transform CJS modules. I’m working on an [ESM loader](https://github.com/eyelidlessness/ts-esbuild-esm-loader) but haven’t had time to get it to release quality. Hopefully I’ll have cycles to get there next weekend 🤞

**Comment by osdevisnot** [comment]
It seems `esbuild-register` works ok, at least with minimal examples I tried it with. Made an example PR in #119.
