### ISSUE TITLE
Remove use of deprecated require.extensions

### ISSUE THREAD

**Issue by benmccann** [lukeed/uvu#82]
`require.extensions` has been deprecated since 0.10.6: https://nodejs.org/api/modules.html#modules_require_extensions

https://github.com/lukeed/uvu/blob/30c10e038e5b99c993f26b93bf411c966a9896eb/examples/svelte/tests/setup/register.js#L22

**Comment by lukeed** [comment]
This is intentional. May be deprecated, but it's how every require hook operates.

**Comment by benmccann** [comment]
@Rich-Harris just suggested in https://github.com/sveltejs/svelte/pull/5770#issuecomment-743221613 that ESM with loader hooks would be a preferable alternative

**Comment by lukeed** [comment]
I can add a separate demonstration for `--loader`, but it only "replaces" `require.extensions` as much ESM replaces CommonJS. It still needs to be an explicit opt-in.
