### ISSUE TITLE
Incompatibility with node's "type: module"

### ISSUE THREAD

**Issue by matt3224** [lukeed/uvu#87]
Hey,

It would appear that if a project uses the `type: module` in package.json then uvu will initially fail with a message like:

```bash
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: type.js
```

If i remove that property from package.json uvu then works as expected, once uvu has then run once for that test file i can go back and re-add `type: module` to package.json. If i then go and add a new test file or edit an existing one i'll have to rinse and repeat

Here's the command i'm using `uvu -r esm src test.js -i _template` and the reason for me using `type: module` is that node wont run esm code without that or renaming files to .mjs

Hoping i've missed something!

Thanks

**Comment by lukeed** [comment]
Hey,

There's a full write up on how to use native esm here: https://github.com/lukeed/uvu/blob/master/docs/esm.md

Using `type: module` can work, but there are aspects to note, especially when _also_ trying to use `esm` module.

Please lemme know if you still have questions/issues!

**Comment by matt3224** [comment]
Got it working now, thanks!
