### ISSUE TITLE
Publish individual packages

### ISSUE THREAD

**Issue by 43081j** [lukeed/uvu#93]
Can you please consider publishing `uvu/assert` as its own standalone package?

Chai is quickly becoming that exhausting blocker in every project. We want to go esm-only but our hand is forced and we need to introduce commonjs support for the sole purpose of being able to import chai...

it would be so nice if we could throw it away and use something more modern - like uvu/assert.

i don't have the time to move our project over to `uvu` as a whole (yet), but could easily switch our assertion library out. 

I suppose, though, that also raises the question: would uvu/assert work with mocha at all?

**Comment by lukeed** [comment]
It should work with it. Error printing may be a bit different, but that should be the only rough edge.

Sorry but a separate package makes no sense. Uvu itself is already pretty small, and `uvu/assert` requires `uvu/diff` to print errors, and those two combined are probably 75% of uvu's size -- 99% if you include the `diff` dependency

Let me know how it works inside mocha :)

**Comment by 43081j** [comment]
fair point, the overhead of pulling the rest of uvu in likely isn't much i suppose.

i'll give it a go and see what happens. if it works, it is a good stepping stone for those of us who can't migrate in one go.

**Comment by 43081j** [comment]
@lukeed it works FYI, haven't run into any problems so far

**Comment by lukeed** [comment]
Cool :)
