### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"

### ISSUE THREAD

**Issue by iwgx** [lukeed/uvu#95]
Hello, I want to integrate `uvu` with my `react-ts` project in `Vite`. But I got this error, am I did something wrong?
I'm just copying the examples in README.

![Screenshot 2021-02-10 011622](https://user-images.githubusercontent.com/20817629/107408548-b348c580-6b3d-11eb-9173-359f15fc73ba.png)
![Screenshot 2021-02-10 011558](https://user-images.githubusercontent.com/20817629/107408554-b5128900-6b3d-11eb-8276-cefdeecda8d6.png)
![Screenshot 2021-02-10 011701](https://user-images.githubusercontent.com/20817629/107408557-b5ab1f80-6b3d-11eb-8780-6f237b30641c.png)

Repro: https://github.com/iwgx/semar/tree/test/uvu

Thanks

**Comment by lukeed** [comment]
You don't have anything in place to transpile the TS contents.

Please see the [typescript example](https://github.com/lukeed/uvu/blob/master/examples/typescript/package.json#L5) – and check out the `tsconfig.json` there too for `ts-node`-specific configuration.

**Comment by iwgx** [comment]
Hi, sorry for disturb again. Is this is the expected output? I mean there is no test name outputted
![Screenshot 2021-02-10 013651](https://user-images.githubusercontent.com/20817629/107411076-af6a7280-6b40-11eb-8e1b-f6c47cc60037.png)

**Comment by lukeed** [comment]
That is correct. You are using `test()` which is an unnamed suite.

The README (and that typescript example I linked) are using named suites (`suite('capitalize')`) and thats why the names were revealed. Suites are basically groups. When everything is passing, you only see the group names & their counts.

You'll only see the individual test names on failures
