### ISSUE TITLE
Better WebStorm Support

### ISSUE THREAD

**Issue by osdevisnot** [lukeed/uvu#96]
hello uvu fans, if you are a WebStorm user and would like better support for running uvu tests, please upvote this feature request here:

https://youtrack.jetbrains.com/issue/WEB-49355

**Comment by lukeed** [comment]
Closing this, as there's nothing actionable that can be done on this side of things.

Thank you for getting things started though :)

**Comment by meoyawn** [comment]
we can write the plugin ourselves. But I'm still not motivated enough

**Comment by lukeed** [comment]
Cool
