### ISSUE TITLE
How to disable colors in output?

### ISSUE THREAD

**Issue by pwespi** [lukeed/uvu#98]
Thanks for this nice package.

Is there a way to disable colors in the output?

I'm using uvu to run tests in the browser, and e.g. in Firefox it looks like this:

```
�[31m✘ �[39m uvu-188078b2.js:2061:10
�[31m  (0 / 1)
�[39m uvu-188078b2.js:2069:8

  �[1m�[41m FAIL �[22m�[49m �[2m"�[22m�[31m�[1mMath.sqrt()�[39m�[22m�[2m"�[22m
    Expected values to be strictly equal:�[3m�[2m  (is)�[23m�[22m

        �[32m++3    �[2m�[3m(Expected)�[22m�[23m�[39m
        �[31m--2    �[2m�[3m(Actual)�[22m�[23m�[39m
        �[90m
    assert@http://localhost:3333/build/uvu-188078b2.js:2238:8
    is@http://localhost:3333/build/uvu-188078b2.js:2246:8
    @http://localhost:3333/build/uvu-188078b2.js:2374:5
    runner@http://localhost:3333/build/uvu-188078b2.js:2053:16
    exec@http://localhost:3333/build/uvu-188078b2.js:2107:39
    promise callback*@http://localhost:3333/build/uvu-188078b2.js:2124:28�[39m


uvu-188078b2.js:2110:10

  Total:     1 uvu-188078b2.js:2116:7
�[31m
  Passed:    0�[39m uvu-188078b2.js:2117:7

  Skipped:   0 uvu-188078b2.js:2118:7

  Duration:  11.00ms
```

**Comment by lukeed** [comment]
Hey, awesome

You can use `--no-color` or `FORCE_COLOR='0'`

But it looks like you're bundling, so you'll have to define/replace `process.env.FORCE_COLOR` as part of your build step

**Comment by lukeed** [comment]
Closing, since this has been answered. Hope the above was able to be help

**Comment by shirakaba** [comment]
I was using `uvu` via the API (not via the CLI) in a NativeScript app with Webpack as the packager (which may also have provided some Node.js stubs), so a fairly hard-to-identify environment.

Defining `FORCE_COLOR` and/or `process.env.FORCE_COLOR` as `"0"` (and various other variations) didn't help, but knowing that it was `kleur` doing the colouring, I found the below to be a simple fix:

```ts
// setup.js

import $ from "kleur";

$.enabled = false;
```

```ts
// index.js

// Import setup.js for effects before running any of your tests.
import "./setup.js";
```
