### ISSUE TITLE
Faking time breaks UVU reports

### ISSUE THREAD

**Issue by haikyuu** [lukeed/uvu#99]
I used `sinon` faking timing functionality 
```
  let clock = sinon.useFakeTimers();
  clock.tick(1000 * 60 * 61);

  clock.restore();
```
And it broke uvu timing
```
  Total:     4
  Passed:    4
  Skipped:   0
  Duration:  -708782213.99ms
```

**Comment by haikyuu** [comment]
I think this is similar to https://github.com/sinonjs/fake-timers/issues/66

**Comment by patricklizon** [comment]
@haikyuu  I had similar issue, at some point I just gave up and used separate `@sinonjs/fake-timers` package.

You could try to play with `before` and `after` methods.

```ts
import { test } from "uvu";
import assert from "uvu/assert";
import FakeTimers from "@sinonjs/fake-timers";

import { debounce } from "../src/debounce";

let clock: FakeTimers.InstalledClock;

test.before(() => {
  clock = FakeTimers.install();
});

test.after(() => {
  clock.uninstall();
});

test("runs function as soon as possible", () => {
  let actual = 0;
  const expected = 1;
  const fun = () => (actual += 1);
  const debouncedFun = debounce(fun, 0);

  debouncedFun();

  assert.is.not(actual, expected);

  clock.tick(0);

  assert.is(actual, expected);
});
```

**Comment by lukeed** [comment]
There is nothing on uvu's end that can be done about this. As per the [Sinon docs](https://sinonjs.org/releases/v9.2.4/fake-timers/): 

> Causes Sinon to replace the **global** `setTimeout`, `clearTimeout`, `setInterval`, `clearInterval`, `setImmediate`, `clearImmediate`, `process.hrtime`, `performance.now`(when available) and `Date` with a custom implementation which is bound to the returned clock object.

(emphasis mine)

It is purposefully mutating the global context with its own implementation(s).
If you don't want to deal with cleanup (though, you should) you could maybe get away with this variant:

```js
var clock = sinon.useFakeTimers({
  toFake: ['setTimeout', ...etc]
})
```

While clearly not as nice to use, uvu uses [`Date.now` for the browser](https://github.com/lukeed/uvu/blob/master/src/index.js#L5) and [`process.hrtime` for Node.js](https://github.com/lukeed/uvu/blob/master/src/index.js#L26) – so those two _cannot_ be fake'd if you want to preserve uvu's reporting.

Here's a related ladder of Sinon snippets, in case you're curious to see what/why this is happening:

1) https://github.com/sinonjs/sinon/blob/master/lib/sinon/sandbox.js#L395-L402
2) -> https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/fake-timers.js#L28-L60
3) -> https://github.com/sinonjs/fake-timers/blob/master/src/fake-timers-src.js#L1282-L1316

My recommendation is to follow @patricklizon's advice, which also echoes the [Sinon docs](https://sinonjs.org/releases/v9.2.4/fake-timers/). This applies to _any_ test runner integration.

```js
test.before(context => {
  context.clock = sinon.useFakeTimers();
});

test.after(context => {
  context.clock.restore();
});
```

Hope that helps~!
